#170 An author will be able to update a blog
atlp-rwanda/atlp-devpulse-bn pull request #171
Opened 2024-12-02 13:30 UTC by mutsinziisaac

### PR Description

This PR adds functionality to allow users to update their blogs and modifies the relevant files to support this feature.

### Description of tasks that were expected to be completed

1. Implement the ability for users to update their own blogs.
2. Update backend routes and controllers to handle blog updates securely and efficiently.
3. Ensure proper validation and authorization checks to prevent unauthorized edits.
4. Previously, there was a vague option for users to update their blogs, leading to challenges in maintaining or correcting their content

### How has this been tested?

Clone the repository.
Checkout the branch ft-updateblog.
Set up the environment variables as indicated in .env.example.
Run npm install followed by npm run dev to start the app.
Test the update functionality on the blog on apollo studio.

### Deployed Link:
https://atlp-devpulse-bn.onrender.com/

### Track PR (Issue number & link):

#170

### ScreenShoot

2024-12-03 08:15 UTC, Philimuhire approved these changes

2024-12-03 09:54 UTC, Ismaelmurekezi approved these changes

2024-12-03 12:55 UTC, Jadowacu1 approved these changes

2024-12-03 14:51 UTC, SaddockAime approved these changes

2024-12-03 14:56 UTC, robsdagreat approved these changes

2024-12-03 21:16 UTC, Mugisha146 approved these changes

2024-12-04 06:25 UTC, MnorbertVii requested changes

2024-12-04 06:25 UTC, MnorbertVii commented on src/models/blogModel.ts
why did you change this?

2024-12-04 06:52 UTC, MnorbertVii approved these changes

2024-12-04 09:19 UTC, Jadowacu1 approved these changes

2024-12-04 13:30 UTC, ncutixavier approved these changes

2024-12-04 13:30 UTC, merged