Ft import and save many trainees from googlesheet v5
atlp-rwanda/atlp-devpulse-bn pull request #37
Opened 2022-11-10 23:42 UTC by Niyonkuru1

## What does this PR do?

Import many trainees and their attributes from google sheet and save them into the mongo database

## Description of Task to be completed?

The admin should copy the URL of his / her google sheet and paste them into the input field of the app, then after hitting load, those data should be copied into the database. If the column of the google sheet is not matching the properties in the database collection, he/she should see the error screen with the steps of how to do it correctly. while if it save correctly, he / she will see the screen saying that uploading is successful.

## How should this be manually tested?

- `Clone the repo`

- `checkout` to branch `ft-import-and-save-many-trainees-from-googlesheet-v5`

- Pull the changes by `git pull`

- Install all packages by running `npm install`

- Start app by `running npm run dev`

## Any background context you want to provide?

Note note **you should use only the configured google sheet url, not every google sheet url will work.**

## What are the relevant pivotal tracker stories?

[Trello Board reference](https://trello.com/c/17S8aqBu/58-import-trainees-google-sheet)

2022-11-16 10:07 UTC, UmuhireJessie commented on src/schema/loadAllTraineesFromGoogleSheet.ts
> +    cohort:String!
we no longer use `cohort`. You might consider removing it

2022-11-16 10:08 UTC, UmuhireJessie commented on src/schema/loadAllTraineesFromGoogleSheet.ts
> +    interview:Int!
Remove `interview` as well

2022-11-16 10:10 UTC, UmuhireJessie commented on src/schema/resendDataIntoDbTypeDefs.ts
> +    interview: String!
`interview` and `interview_decision`?

2022-11-16 10:14 UTC, UmuhireJessie requested changes
- Considering the following 

```
{
  "spreadsheetId": "1nltXpm-_7FyIfCwcpd4qYNeXP-tewPRwXaYggRcBDHM"
}
```

- I have this as an output, not sure why `cycle_id` is becoming null

![image](https://user-images.githubusercontent.com/86103578/202152979-2bf6a3fe-e405-49cf-9530-fb99ee5eb94c.png)

2022-11-16 14:37 UTC, mugiisha commented
the functionality works well on a successful attempt
**issues**
#### successful message toast on an unsuccessful attempt
![pops](https://user-images.githubusercontent.com/88486212/202208340-bcab2857-eea5-432e-bfce-6dc2c5c09f63.png)
#### resend query button not functioning
![reseeend](https://user-images.githubusercontent.com/88486212/202208766-dd8266b3-e8fc-4ad4-97b3-0ca9bbb31836.png)
_after a failed attempt one have to refresh the page to try again_

2022-11-16 15:54 UTC, kareraolivier requested changes
# squash the commit @Hodal66

2022-11-17 12:04 UTC, UmuhireJessie requested changes
See comments!

2022-11-17 16:15 UTC, merged