Apllication cycle
atlp-rwanda/atlp-devpulse-bn pull request #5
Opened 2022-09-27 15:08 UTC by kareraolivier

### **What does this PR do?**
this PR provides Application cycle

### **How should this be manually tested?**

• Run `git clone https://github.com/atlp-rwanda/atlp-devpulse-bn` to clone the project

• Run `cd atlp-devpulse-bn` to go to the root project

• Run `git checkout ch-tapplication-cycle`

• Run `npm i` or `npm instal`l to install all used dependencies

• Run `npm run dev` to start the server
### **What to expect?**
traineeAttributes model will be imported to be used to hold data

- [ ] Data in database

<img width="968" alt="Screen Shot 2022-09-27 at 14 26 33" src="https://user-images.githubusercontent.com/77101006/192526088-a9f142f2-4281-4cae-bea1-16bc386897a2.png">

2022-09-27 20:51 UTC, tysepa approved these changes

2022-09-28 15:45 UTC, Salim-54 requested changes
Relocate codes from **src/schema/index.ts** and import them there instead!
others look alright

2022-09-29 09:31 UTC, Salim-54 approved these changes

2022-09-29 12:07 UTC, GilbertUp approved these changes

2022-09-29 14:28 UTC, denislohan requested changes
Could you explain more in the description, what this PR does?

2022-09-29 16:06 UTC, denislohan approved these changes

2022-09-30 13:40 UTC, merged