fix develop
atlp-rwanda/atlp-devpulse-bn pull request #60
Opened 2023-08-09 10:00 UTC by buka1calvin

user should be able to login using google with hosted version

2023-08-09 10:04 UTC, JosephNgabo approved these changes

2023-08-09 10:31 UTC, nkurunziza1 approved these changes

2023-08-14 08:02 UTC, mjeanbosco19 requested changes
@buka1calvin I tested this PR. When I click Sign with Google button, it open sign URL but it does return anything, even if I tried to refresh, still I was not able to sign in.

2023-11-08 10:37 UTC, closed without merging

2023-11-08 10:38 UTC, Anguandia commented
Stale, purpose implemented elsewhere