ft(application-form):application form for new applicants
atlp-rwanda/atlp-devpulse-bn pull request #64
Opened 2023-08-27 07:01 UTC by ba-lambert

2023-08-30 09:24 UTC, dean-daryl approved these changes

2023-08-30 11:56 UTC, JENNY-257 approved these changes

2023-08-30 11:57 UTC, JENNY-257 approved these changes

2023-08-30 13:20 UTC, JosephNgabo approved these changes

2023-08-30 13:57 UTC, JosephNgabo commented
there is some conflicts in index.ts you can resolve them

2023-08-30 15:38 UTC, Anguandia requested changes

2023-08-30 15:38 UTC, Anguandia commented on credentials.json
>    }
Wouldn't we rather keep the credential values in the environment?

2023-08-30 15:38 UTC, Anguandia commented on src/models/newApplications.ts
How shall we validate some items as required, considering conditional form flow? For example, if the value for "currentlyStudying" is False, then Required for education level is False. Please let's get together as a focus group and brainstorm this

2023-10-26 16:35 UTC, Anguandia commented
@ba-lambert , should we close this PR? if the functionality is already implemented through another proxy, please confirm asap

2023-11-08 10:36 UTC, closed without merging