feature(superAdmin must register a user)
atlp-rwanda/atlp-devpulse-bn pull request #67
Opened 2023-09-08 00:32 UTC by buka1calvin

2023-09-13 11:33 UTC, nkurunziza1 approved these changes

2023-09-14 14:34 UTC, katros1 approved these changes

2023-09-15 06:08 UTC, JENNY-257 approved these changes

2023-09-15 08:13 UTC, Anguandia requested changes
Good work @buka1calvin , just one thing, your tests are failing here, please investigate and rectify
<img width="1134" alt="Screenshot 2023-09-15 at 10 10 00" src="https://github.com/atlp-rwanda/atlp-devpulse-bn/assets/36167006/0092772e-6ad1-429f-968d-0cd4d48d321a">

2023-09-15 09:56 UTC, dean-daryl approved these changes

2023-09-15 10:11 UTC, Anguandia approved these changes

2023-09-15 10:12 UTC, merged