Feature: Add individual trainee-applicants.
atlp-rwanda/atlp-devpulse-bn pull request #7
Opened 2022-09-28 16:00 UTC by Salim-54

### **What does this PR do?**
this PR Add individual trainee-applicants.

### **How should this be manually tested?**

• Run `git clone https://github.com/atlp-rwanda/atlp-devpulse-bn` to clone the project

• Run `cd atlp-devpulse-bn` to go to the root project

• Run `git checkout ft-trainee-applicant-CRUD`

• Run `npm i` or `npm instal`l to install all used dependencies

• Run `npm run dev` to start the server
### **What to expect?**
To add a trainee applicant to new application cycle
- [ ] apollo sandbox

![add](https://user-images.githubusercontent.com/81898585/192824040-acb8f968-a99d-4d88-b1a5-eb51474db2b0.png)

2022-10-03 15:43 UTC, Hodal66 approved these changes

2022-10-03 15:44 UTC, Hodal66 commented
Resolve Conflict !!!

2022-10-03 16:08 UTC, kareraolivier requested changes
I can see you have 5 commits:

- [x] squash them into one 
- [ ] push again

2022-10-04 22:23 UTC, tysepa approved these changes

2022-10-05 20:20 UTC, closed without merging